### ISSUE TITLE
[Meta] Peer Connectivity

### ISSUE THREAD

**Issue by GregTheGreek** [ultralight-beam/UB.swift#24]
# Objective
Get two or more devices to peer with one another over bluetooth.

 # Related Issues
- [x] [Core Bluetooth transport implementation](https://github.com/ultralight-beam/UB.swift/issues/25) (#25)
- [x] [Message Passing](https://github.com/ultralight-beam/UB.swift/issues/26)
- [x] [Peer Discovery](https://github.com/ultralight-beam/UB.swift/issues/27)
